# Generated by Django 3.1.14 on 2022-09-21 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contentshub', '0002_auto_20220922_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_master', to='accounts.user', verbose_name='유저'),
            preserve_default=False,
        ),
    ]
